// client/src/config/schoolConfig.js
// AUTO-GENERATED by scripts/build-foundation.js — do not edit by hand.

const schoolConfig = {
  "universityId": null,
  "foundationName": "Abacco Technology",
  "appName": "Abacco School App",
  "foundationKey": "global",
  "address": "No 12,13 & 12/A, Kirthan Arcade, 3rd Floor, Aditya Nagar, Sandeep Unnikrishnan Road, Bangalore — 560097",
  "Phone": "+91 7204986825, +91 9972452044"
};

export default schoolConfig;
